### ISSUE TITLE
paribu api update

### ISSUE THREAD

**Issue by serensoner** [burakoner/Paribu.Api#1]
merhabalar, oncelikle bu reverse engineering calismasi ve paylasim icin tesekkurler. bu repository acaba paribu'nun guncellenmesinden sonra halen calisiyor mu? backend'in biraz degistirildigini gordum de.

tesekkurler

**Comment by burakoner** [comment]
Hayır. Ancak Paribu'nun yeni versiyonunda kullandığı altyapıyı belirledim. Birkaç güne Paribu.Api'yi bu bağlamda update edeceğim. Paribu.Net zaten artık arşiv modunda.

**Comment by serensoner** [comment]
Tesekkurler hem cevap hem de paylasim icin. Bu devirde API doc paylasmayan borsa olmasi, ve bunu reverse engineer etmek zorunda kalmak aci ama bir yandan da eglenceli.

Not: En son bunu Thodex icin yapmistim, yaptiktan 2 hafta sonra olanlar ortada. Umarim aynisi olmaz :)

Iyi calismalar
